{{- if not .Values.telegram.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-bot-api.apiSecretName" . }}
  labels:
    {{- include "telegram-bot-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.telegram.apiIdKey }}: {{ .Values.telegram.apiId | quote }}
  {{ .Values.telegram.apiHashKey }}: {{ .Values.telegram.apiHash | quote }}
{{- end }}
{{- if and .Values.basicAuth.enabled (not .Values.basicAuth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-bot-api.basicAuthSecretName" . }}
  labels:
    {{- include "telegram-bot-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth: |-
    {{- required "basicAuth.auth is required when basicAuth.enabled=true and basicAuth.existingSecret is empty" .Values.basicAuth.auth | nindent 4 }}
{{- end }}
