apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegram-bot-api.fullname" . }}
  labels:
    {{- include "telegram-bot-api.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "telegram-bot-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      protocol: TCP
      targetPort: http
    - name: http-stat
      port: {{ .Values.service.ports.stat }}
      protocol: TCP
      targetPort: http-stat
